commit 8 - test 3

diff --git a/.github/workflows/debugger_workflow.yml b/.github/workflows/debugger_workflow.yml
--- a/.github/workflows/debugger_workflow.yml
+++ b/.github/workflows/debugger_workflow.yml
@@ -36,12 +36,13 @@ jobs:
           echo "- BRANCH_STG3: ${{ vars.BRANCH_STG3 }}" >> $GITHUB_STEP_SUMMARY
 
       - name: Validate Environment Variable 
+        shell: bash
         run: |
-          if not "%ENVIRONMENT_NAME%" == "STG-1" if not "%ENVIRONMENT_NAME%" == "STG-2" if not "%ENVIRONMENT_NAME%" == "STG-3" (
-            echo ### Error setting environment :x: >> %GITHUB_STEP_SUMMARY%
-            echo A branch that is being used is not being targeted to any environment: Update the BRANCH_STGX repository variable that best applies to this merge. >> %GITHUB_STEP_SUMMARY%
-            exit /b 1
-          )
+          if [[ "${{ env.ENVIRONMENT_NAME }}" != "STG-1" && "${{ env.ENVIRONMENT_NAME }}" != "STG-2" && "${{ env.ENVIRONMENT_NAME }}" != "STG-3" ]]; then
+            echo "### Error setting environment :x:" >> $GITHUB_STEP_SUMMARY
+            echo "A branch that is being used is not being targeted to any environment: Update the BRANCH_STGX repository variable that best applies to this merge." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
       - name: Show Environment
         run: |
